name: Build and deploy Node.js app to Azure Web App - hashsports-server

on:
  push:
    branches:
      - backend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to Azure Web App
        id: deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'hashsports-server'
          package: '${{ github.workspace }}/'
          
      - name: Retry deployment if conflict
        if: steps.deploy.outcome == 'failure'
        run: |
          echo "Deployment conflict detected, retrying after delay..."
          sleep 60
          n=0
          until [ "$n" -ge 5 ]
          do
            az webapp deployment source config-zip --resource-group hashan789 --name hashsports-server --src '${{ github.workspace }}/' && break
            n=$((n+1))
            echo "Retry $n/5 failed, retrying in 60 seconds..."
            sleep 60
          done
